routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('items', 'ItemsController');

Route::resource('legajos', 'LegajosController');

Route::resource('tipoTareas', 'TipoTareaController');

Route::resource('tareas', 'TareasController');

Route::get('tareas/filtrar/{status}/{lote}', 'TareasController@index')->name('status');

Route::post('buscarTareas','TareasController@buscarTareas');

Route::resource('stocks', 'StockController');

Route::resource('legajoGps', 'LegajoGpsController');

Route::resource('anomaliases', 'AnomaliasController');

Route::resource('clientes', 'ClientesController');

Route::resource('users', 'UsersController');

Route::get('importarTareas','TareasController@loadTasks');
Route::post('saveRuta','TareasController@saveRuta');

Route::get('modificarRutas','TareasController@modificarRutas');

Route::post('saveRoutes/rutas','TareasController@saveRutas');

Route::post('saveRoutesPolygon/rutas','TareasController@guardarRutasPoly');

Route::resource('inputFormats', 'InputFormatsController');

Route::resource('taskTypes', 'TaskTypesController');

Route::resource('subTasks', 'SubTasksController');

Route::resource('materialTypes', 'MaterialTypesController');

Route::resource('flotillas', 'FlotillasController');

Route::resource('flotillasUsuarios', 'FlotillasUsuariosController');


Route::get('/api/token', 'Api\TokenController@index');

Route::post('/api/user/register', 'Api\UserController@register');
Route::post('/api/user/login', 'Api\UserController@login');
Route::post('/api/user/token_login', 'Api\UserController@token_login');
Route::get('/api/user/logout', 'Api\UserController@logout');
Route::get('/api/fcm/register', 'Api\UserController@fcm_register');
Route::get('/api/user_location', 'Api\LocationController@register_location');
Route::get('/api/user_medidores/{user_id}','Api\UserController@getMedidores');
Route::get('/api/get_face_ids', 'Api\UserController@get_face_ids');
Route::get('/api/download/{file_name}', 'Api\UserController@download_face_ids');

Route::resource('/api/task', 'Api\TaskController');
Route::get('/api/my_task/{id}', 'Api\TaskController@index');
Route::post('/api/task/start', 'Api\TaskController@start_task');
Route::post('/api/task/finish', 'Api\TaskController@finish_task');
Route::post('/api/task/photo', 'Api\TaskController@post_task_photo');
Route::post('/api/task/set_anomaly', 'Api\TaskController@set_anomaly');
Route::get('/api/test', 'Api\TaskController@test');

Route::get('/api/stock/{id}', 'Api\StockController@index');

Route::get('/api/stock_item/{barcode}/{id}', 'Api\StockController@search_item');
Route::post('/api/my_stock_items/check', 'Api\StockController@check_used_item');
Route::get('/api/users/{user_id}', 'Api\UserController@index');

// Order
Route::post('/api/order/process', 'Api\OrderController@process_order');
Route::post('/api/order/accept', 'Api\OrderController@accept_order');
Route::get('/api/order/pending', 'Api\OrderController@get_pending_orders');
Route::get('/api/order/{user_id}', 'Api\OrderController@get_confirm_orders');
Route::get('/api/order/{user_id}/proceeded', 'Api\OrderController@get_proceeded_orders');
Route::get('/api/order/{user_id}/set_check', 'Api\OrderController@set_check_proceeded_orders');
Route::get('/api/order/{user_id}/{order_id}/set_check', 'Api\OrderController@set_check_pended_order');

Route::get('/api/send/{msg}', 'Api\OrderController@send_msg');

Route::get('/seguimiento','FlotillasController@seguimientoGps');
Route::get('/seguir/{id}','FlotillasController@seguir');

Route::resource('marcas', 'MarcasController');

Route::resource('modelos', 'ModelosController');


Route::resource('medidores', 'MedidoresController');
Route::post('medidoresAssign/{id}','MedidoresController@assignTo');
Route::get('changeState/{id}/{state}','MedidoresController@changeState');


Route::post('saveNewGeo','TareasController@newGeo');
Route::post('asignarMedidores','MedidoresController@asignarMultiples');

route::get('imprimirTarea/{id}','TareasController@imprimirTarea');

app/Http/Controllers/TaskTypesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTaskTypesRequest;
use App\Http\Requests\UpdateTaskTypesRequest;
use App\Models\SubTasks;
use App\Models\TaskTypes;
use App\Repositories\TaskTypesRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class TaskTypesController extends AppBaseController
{
    /** @var  TaskTypesRepository */
    private $taskTypesRepository;

    public function __construct(TaskTypesRepository $taskTypesRepo)
    {
        $this->taskTypesRepository = $taskTypesRepo;
    }

    /**
     * Display a listing of the TaskTypes.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->taskTypesRepository->pushCriteria(new RequestCriteria($request));
        $taskTypes = $this->taskTypesRepository->all();

        return view('task_types.index')
            ->with('taskTypes', $taskTypes);
    }

    /**
     * Show the form for creating a new TaskTypes.
     *
     * @return Response
     */
    public function create()
    {
        return view('task_types.create');
    }

    /**
     * Store a newly created TaskTypes in storage.
     *
     * @param CreateTaskTypesRequest $request
     *
     * @return Response
     */
    public function store(CreateTaskTypesRequest $request)
    {
        $input = $request->all();


        $taskTypes = new TaskTypes();
        $taskTypes->name = $input['name'];
        $taskTypes->alias = $input['alias'];
        $taskTypes->cliente = $input['cliente'];
        $taskTypes->precio = $input['precio'];
        $taskTypes->max_time = $input['max_time'];
        $taskTypes->priority = $input['priority'];
        $taskTypes->workersRequired = $input['workersRequired'];
        $taskTypes->save();
        foreach($input['subtasks'] as $subtask){
            $newSubTask = new SubTasks();
            $newSubTask->name = $subtask['nombre'];
            $newSubTask->max_time = $subtask['max_time'];
            $newSubTask->precio = $subtask['precio'];
            $newSubTask->alias = $subtask['alias'];
            $newSubTask->workersRequired = $subtask['workersRequired'];
            $newSubTask->taskType = $taskTypes->id;
            $newSubTask->save();
        }

        Flash::success('Task Types saved successfully.');

        return redirect(route('taskTypes.index'));
    }

    /**
     * Display the specified TaskTypes.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $taskTypes = $this->taskTypesRepository->findWithoutFail($id);

        if (empty($taskTypes)) {
            Flash::error('Task Types not found');

            return redirect(route('taskTypes.index'));
        }

        return view('task_types.show')->with('taskTypes', $taskTypes);
    }

    /**
     * Show the form for editing the specified TaskTypes.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $taskTypes = $this->taskTypesRepository->findWithoutFail($id);

        if (empty($taskTypes)) {
            Flash::error('Task Types not found');

            return redirect(route('taskTypes.index'));
        }

        return view('task_types.edit')->with('taskTypes', $taskTypes);
    }

    /**
     * Update the specified TaskTypes in storage.
     *
     * @param  int              $id
     * @param UpdateTaskTypesRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTaskTypesRequest $request)
    {
        $taskTypes = $this->taskTypesRepository->findWithoutFail($id);

        $input = $request->all();
        if (empty($taskTypes)) {
            Flash::error('Task Types not found');

            return redirect(route('taskTypes.index'));
        }

//        $taskTypes = $this->taskTypesRepository->update($request->all(), $id);

        $taskTypes->name = $input['name'];
        $taskTypes->alias = $input['alias'];
        $taskTypes->cliente = $input['cliente'];
        $taskTypes->precio = $input['precio'];
        $taskTypes->max_time = $input['max_time'];
        $taskTypes->priority = $input['priority'];
        $taskTypes->workersRequired = $input['workersRequired'];
        $taskTypes->save();
        $taskTypes->subTasks()->delete();
        foreach($input['subtasks'] as $subtask){
            $newSubTask = new SubTasks();
            $newSubTask->name = $subtask['nombre'];
            $newSubTask->max_time = $subtask['max_time'];
            $newSubTask->precio = $subtask['precio'];
            $newSubTask->alias = $subtask['alias'];
            $newSubTask->workersRequired = $subtask['workersRequired'];
            $newSubTask->taskType = $taskTypes->id;
            $newSubTask->save();
        }

        Flash::success('Task Types updated successfully.');

        return redirect(route('taskTypes.index'));
    }

    /**
     * Remove the specified TaskTypes from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $taskTypes = $this->taskTypesRepository->findWithoutFail($id);

        if (empty($taskTypes)) {
            Flash::error('Task Types not found');

            return redirect(route('taskTypes.index'));
        }

        $this->taskTypesRepository->delete($id);

        Flash::success('Task Types deleted successfully.');

        return redirect(route('taskTypes.index'));
    }
}

resources/views/task_types/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Servicios
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'taskTypes.store']) !!}

                        @include('task_types.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/task_types/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Servicios
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($taskTypes, ['route' => ['taskTypes.update', $taskTypes->id], 'method' => 'patch']) !!}

                        @include('task_types.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/task_types/fields.blade.php
<style>
    .subtaskRenglon{
        margin:40px 0px;
    }
</style>
<script>
    function addField(){
        fieldId = $('.subtaskRenglon').length;
        $('#subtareas').append('<div class="row subtaskRenglon"><div class="col-md-1">#'+(fieldId+1)+'</div><div class="col-md-11"><div class="camposRow">'+
                '<div class="col-md-12">'+
                    '<label>Nombre</label>' +
                    '<input type="text" class="form-control" name="subtasks['+fieldId+'][nombre]">'+
                '</div>'+
                '<div class="col-md-6 hidden" >' +
                    '<label>Limite de tiempo de ejecución</label>' +
                    '<input type="text" class="form-control timeExecuting" name="subtasks['+fieldId+'][max_time]" value="0">' +
                '</div>' +
                '<div class="col-md-6">' +
                    '<label>Precio</label>' +
                    '<div class="input-group">'+
                    '<span class="input-group-addon">$</span>'+
                    '<input type="text" class="form-control precio" name="subtasks['+fieldId+'][precio]" value="0">' +
                '</div>'+
                '<div class="col-md-6">' +
                    '<label>Alias</label>' +
                    '<div class="input-group">'+
                    '<input type="text" class="form-control alias" name="subtasks['+fieldId+'][alias]" value="0">' +
                    '</div>'+
                '</div>' +
                '<div class="col-md-6 hidden" >' +
                    '<label>Operadores necesarios</label>' +
                    '<input type="number" class="form-control workersRequired" min="1" name="subtasks['+fieldId+'][workersRequired]" value="1">' +
                '</div>' +
            '</div></div></div>');

    }
</script>
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Nombre:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group col-sm-6">
    {!! Form::label('alias', 'Alias (como viene en el excel):') !!}
    {!! Form::text('alias', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group col-sm-6">
    {!! Form::label('cliente', 'Cliente:') !!}
    {!! Form::select('cliente', \App\Models\Clientes::get()->pluck('nombre','id')->toArray(), null, ['class' => 'form-control']) !!}
</div>

<!-- Max Time Field -->
<div class="form-group col-sm-6 hidden">
    {!! Form::label('max_time', 'Tiempo máximo de ejecución(horas):') !!}
    {!! Form::number('max_time', 0, ['class' => 'form-control']) !!}
    <label class="subtext" style="color:red">*ingresar 0 para indefinido</label>
</div>
<div class="form-group col-sm-6">

    {!! Form::label('precio', 'Costo Base:') !!}
    <div class="input-group">
        <span class="input-group-addon">$</span>
        {!! Form::text('precio', null, ['class' => 'form-control']) !!}

    </div>
</div>
<!-- Priority Field -->
<div class="form-group col-sm-6">
    {!! Form::label('priority', 'Prioridad:') !!}
    {!! Form::select('priority', ['l'=>'Baja','m'=>'Media','h'=>'Alta','u'=>'Urgente','e'=>'Emergente'],null, ['class' => 'form-control']) !!}
</div>

<!-- Workersrequired Field -->
<div class="form-group col-sm-6 hidden">
    {!! Form::label('workersRequired', 'Operadores necesarios:') !!}
    {!! Form::number('workersRequired', 1, ['class' => 'form-control','min'=>1]) !!}
</div>
<div class="form-group col-md-12">
    <hr>
    {!! Form::label('subtasks', 'Parametros:') !!}
    <br>
    <div class="col-md-12" id="subtareas">
        @if(!empty($taskTypes))
            @foreach($taskTypes->subtasks as $k=>$subtask)
                <input type="hidden" value="{{$subtask->id}}" name="id">
                <div class="row subtaskRenglon" id="row_{{$subtask->id}}">
                    <div class="col-md-1">
                        <a href="javascript:$('#row_{{$subtask->id}}').remove()" class="label label-danger">X</a>#{{$k+1}}</div>
                    <div class="col-md-11">
                        <div class="camposRow">
                            <div class="col-md-12">
                                <label>Nombre</label>
                                <input type="text" class="form-control" name="subtasks[{{$k}}][nombre]" value="{{$subtask->name}}">
                            </div>
                            <div class="col-md-6">
                                <label>Precio</label>
                                <input type="text" class="form-control precio" name="subtasks[{{$k}}][precio]" value="{{$subtask->precio}}">
                            </div>
                            <div class="col-md-6">
                                <label>Alias</label>
                                <input type="text" class="form-control alias" name="subtasks[{{$k}}][alias]" value="{{$subtask->alias}}">
                            </div>
                            <div class="col-md-6 hidden">
                                <label>Limite de tiempo de ejecución</label>
                                <input type="text" class="form-control timeExecuting" name="subtasks[{{$k}}][max_time]" value="{{$subtask->max_time}}">
                            </div>
                            <div class="col-md-6 hidden">
                                <label>Operadores necesarios</label>
                                <input type="number" class="form-control workersRequired" min="1" name="subtasks[{{$k}}][workersRequired]" value="{{$subtask->workersRequired}}">
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        @endif
    </div>
    <a href="javascript:addField()" class="btn btn-default"> + Agregar parametro</a><br><br>

</div>
<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('taskTypes.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/task_types/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Servicios</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('taskTypes.create') !!}">Nuevo</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('task_types.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/task_types/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Task Types
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('task_types.show_fields')
                    <a href="{!! route('taskTypes.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/task_types/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $taskTypes->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $taskTypes->name !!}</p>
</div>

<!-- Max Time Field -->
<div class="form-group">
    {!! Form::label('max_time', 'Max Time:') !!}
    <p>{!! $taskTypes->max_time !!}</p>
</div>

<!-- Priority Field -->
<div class="form-group">
    {!! Form::label('priority', 'Priority:') !!}
    <p>{!! $taskTypes->priority !!}</p>
</div>

<!-- Workersrequired Field -->
<div class="form-group">
    {!! Form::label('workersRequired', 'Workersrequired:') !!}
    <p>{!! $taskTypes->workersRequired !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $taskTypes->deleted_at !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $taskTypes->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $taskTypes->updated_at !!}</p>
</div>

resources/views/task_types/table.blade.php
@php($prioridades = ['l'=>'Baja','m'=>'Media','h'=>'Alta','u'=>'Urgente','e'=>'Emergente'])
<script>
    $(document).ready( function () {
        var table = $('.table').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
            }
        } )
    });
</script>
<table class="table table-responsive" id="taskTypes-table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Alias</th>
            <th>Cliente</th>
            <th>Subtareas</th>
            <th>Tiempo Maximo de Trabajo</th>
            <th>Prioridad</th>
            <th>Operadores requeridos</th>
            <th>Accion</th>
        </tr>
    </thead>
    <tbody>
    @foreach($taskTypes as $taskTypes)
        <tr>
            <td>{!! $taskTypes->name !!}</td>
            <td>{!! $taskTypes->alias !!}</td>
            <td>{!! \App\Models\Clientes::find($taskTypes->cliente)->nombre !!}</td>
            <td>{{count($taskTypes->subtasks)}}</td>
            <td>{!! $taskTypes->max_time !!}</td>
            <td>{!! $prioridades[$taskTypes->priority] !!}</td>
            <td>{!! $taskTypes->workersRequired !!}</td>
            <td>
                {!! Form::open(['route' => ['taskTypes.destroy', $taskTypes->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('taskTypes.edit', [$taskTypes->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Estas seguro?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>