routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('items', 'ItemsController');

Route::resource('legajos', 'LegajosController');

Route::resource('tipoTareas', 'TipoTareaController');

Route::resource('tareas', 'TareasController');

Route::get('tareas/filtrar/{status}/{lote}', 'TareasController@index')->name('status');

Route::post('buscarTareas','TareasController@buscarTareas');

Route::resource('stocks', 'StockController');

Route::resource('legajoGps', 'LegajoGpsController');

Route::resource('anomaliases', 'AnomaliasController');

Route::resource('clientes', 'ClientesController');

Route::resource('users', 'UsersController');

Route::get('importarTareas','TareasController@loadTasks');
Route::post('saveRuta','TareasController@saveRuta');

Route::get('modificarRutas','TareasController@modificarRutas');

Route::post('saveRoutes/rutas','TareasController@saveRutas');

Route::post('saveRoutesPolygon/rutas','TareasController@guardarRutasPoly');

Route::resource('inputFormats', 'InputFormatsController');

Route::resource('taskTypes', 'TaskTypesController');

Route::resource('subTasks', 'SubTasksController');

Route::resource('materialTypes', 'MaterialTypesController');

Route::resource('flotillas', 'FlotillasController');

Route::resource('flotillasUsuarios', 'FlotillasUsuariosController');


Route::get('/api/token', 'Api\TokenController@index');

Route::post('/api/user/register', 'Api\UserController@register');
Route::post('/api/user/login', 'Api\UserController@login');
Route::post('/api/user/token_login', 'Api\UserController@token_login');
Route::get('/api/user/logout', 'Api\UserController@logout');
Route::get('/api/fcm/register', 'Api\UserController@fcm_register');
Route::get('/api/user_location', 'Api\LocationController@register_location');
Route::get('/api/user_medidores/{user_id}','Api\UserController@getMedidores');
Route::get('/api/get_face_ids', 'Api\UserController@get_face_ids');
Route::get('/api/download/{file_name}', 'Api\UserController@download_face_ids');

Route::resource('/api/task', 'Api\TaskController');
Route::get('/api/my_task/{id}', 'Api\TaskController@index');
Route::post('/api/task/start', 'Api\TaskController@start_task');
Route::post('/api/task/finish', 'Api\TaskController@finish_task');
Route::post('/api/task/photo', 'Api\TaskController@post_task_photo');
Route::post('/api/task/set_anomaly', 'Api\TaskController@set_anomaly');
Route::get('/api/test', 'Api\TaskController@test');

Route::get('/api/stock/{id}', 'Api\StockController@index');

Route::get('/api/stock_item/{barcode}/{id}', 'Api\StockController@search_item');
Route::post('/api/my_stock_items/check', 'Api\StockController@check_used_item');
Route::get('/api/users/{user_id}', 'Api\UserController@index');

// Order
Route::post('/api/order/process', 'Api\OrderController@process_order');
Route::post('/api/order/accept', 'Api\OrderController@accept_order');
Route::get('/api/order/pending', 'Api\OrderController@get_pending_orders');
Route::get('/api/order/{user_id}', 'Api\OrderController@get_confirm_orders');
Route::get('/api/order/{user_id}/proceeded', 'Api\OrderController@get_proceeded_orders');
Route::get('/api/order/{user_id}/set_check', 'Api\OrderController@set_check_proceeded_orders');
Route::get('/api/order/{user_id}/{order_id}/set_check', 'Api\OrderController@set_check_pended_order');

Route::get('/api/send/{msg}', 'Api\OrderController@send_msg');

Route::get('/seguimiento','FlotillasController@seguimientoGps');
Route::get('/seguir/{id}','FlotillasController@seguir');

Route::resource('marcas', 'MarcasController');

Route::resource('modelos', 'ModelosController');


Route::resource('medidores', 'MedidoresController');
Route::post('medidoresAssign/{id}','MedidoresController@assignTo');
Route::get('changeState/{id}/{state}','MedidoresController@changeState');


Route::post('saveNewGeo','TareasController@newGeo');
Route::post('asignarMedidores','MedidoresController@asignarMultiples');

route::get('imprimirTarea/{id}','TareasController@imprimirTarea');

app/Http/Controllers/MaterialTypesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateMaterialTypesRequest;
use App\Http\Requests\UpdateMaterialTypesRequest;
use App\Repositories\MaterialTypesRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class MaterialTypesController extends AppBaseController
{
    /** @var  MaterialTypesRepository */
    private $materialTypesRepository;

    public function __construct(MaterialTypesRepository $materialTypesRepo)
    {
        $this->materialTypesRepository = $materialTypesRepo;
    }

    /**
     * Display a listing of the MaterialTypes.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->materialTypesRepository->pushCriteria(new RequestCriteria($request));
        $materialTypes = $this->materialTypesRepository->all();

        return view('material_types.index')
            ->with('materialTypes', $materialTypes);
    }

    /**
     * Show the form for creating a new MaterialTypes.
     *
     * @return Response
     */
    public function create()
    {
        return view('material_types.create');
    }

    /**
     * Store a newly created MaterialTypes in storage.
     *
     * @param CreateMaterialTypesRequest $request
     *
     * @return Response
     */
    public function store(CreateMaterialTypesRequest $request)
    {
        $input = $request->all();

        $materialTypes = $this->materialTypesRepository->create($input);

        Flash::success('Material Types saved successfully.');

        return redirect(route('materialTypes.index'));
    }

    /**
     * Display the specified MaterialTypes.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $materialTypes = $this->materialTypesRepository->findWithoutFail($id);

        if (empty($materialTypes)) {
            Flash::error('Material Types not found');

            return redirect(route('materialTypes.index'));
        }

        return view('material_types.show')->with('materialTypes', $materialTypes);
    }

    /**
     * Show the form for editing the specified MaterialTypes.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $materialTypes = $this->materialTypesRepository->findWithoutFail($id);

        if (empty($materialTypes)) {
            Flash::error('Material Types not found');

            return redirect(route('materialTypes.index'));
        }

        return view('material_types.edit')->with('materialTypes', $materialTypes);
    }

    /**
     * Update the specified MaterialTypes in storage.
     *
     * @param  int              $id
     * @param UpdateMaterialTypesRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMaterialTypesRequest $request)
    {
        $materialTypes = $this->materialTypesRepository->findWithoutFail($id);

        if (empty($materialTypes)) {
            Flash::error('Material Types not found');

            return redirect(route('materialTypes.index'));
        }

        $materialTypes = $this->materialTypesRepository->update($request->all(), $id);

        Flash::success('Material Types updated successfully.');

        return redirect(route('materialTypes.index'));
    }

    /**
     * Remove the specified MaterialTypes from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $materialTypes = $this->materialTypesRepository->findWithoutFail($id);

        if (empty($materialTypes)) {
            Flash::error('Material Types not found');

            return redirect(route('materialTypes.index'));
        }

        $this->materialTypesRepository->delete($id);

        Flash::success('Material Types deleted successfully.');

        return redirect(route('materialTypes.index'));
    }
}

resources/views/material_types/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Tipo de Materiales
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'materialTypes.store']) !!}

                        @include('material_types.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/material_types/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Tipo de Materiales
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($materialTypes, ['route' => ['materialTypes.update', $materialTypes->id], 'method' => 'patch']) !!}

                        @include('material_types.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/material_types/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Nombre:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>
<!-- Max Uses Field -->
<div class="form-group col-sm-6">
    {!! Form::label('max_uses', 'Usos máximos:') !!}
    {!! Form::number('max_uses', null, ['class' => 'form-control']) !!}
</div>
<!-- Marca Field -->
<div class="form-group col-sm-6">
    {!! Form::label('marca', 'Marca:') !!}
    {!! Form::select('marca',array_merge(['0' => 'Seleccione'], \App\Models\Marcas::get()->pluck('nombre','id')->toArray() ) ,null, ['class' => 'form-control']) !!}
</div>
<!-- Modelo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('modelo', 'Modelo:') !!}
    {!! Form::select('modelo',array_merge(['0' => 'Seleccione'], \App\Models\Modelos::get()->pluck('nombre','id')->toArray())  ,null, ['class' => 'form-control']) !!}
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('materialTypes.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/material_types/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Tipo de Materiales</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('materialTypes.create') !!}">Nuevo</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('material_types.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/material_types/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Material Types
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('material_types.show_fields')
                    <a href="{!! route('materialTypes.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/material_types/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $materialTypes->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $materialTypes->name !!}</p>
</div>

<!-- Max Uses Field -->
<div class="form-group">
    {!! Form::label('max_uses', 'Max Uses:') !!}
    <p>{!! $materialTypes->max_uses !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $materialTypes->deleted_at !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $materialTypes->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $materialTypes->updated_at !!}</p>
</div>

resources/views/material_types/table.blade.php
<script>
    $(document).ready( function () {
        var table = $('.table').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
            }
        } )
    });
</script>
<table class="table table-responsive" id="materialTypes-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Max Uses</th>
            <th>Acción</th>
        </tr>
    </thead>
    <tbody>
    @foreach($materialTypes as $materialTypes)
        <tr>
            @php($marca = \App\Models\Marcas::find($materialTypes->marca))
            @php($modelo = \App\Models\Modelos::find($materialTypes->modelo))
            <td>{!! $materialTypes->name !!}</td>
            <td>{{ empty($marca)?'':$marca->nombre }}</td>
            <td>{{ empty($modelo)?'':$modelo->nombre }}</td>
            <td>{!! $materialTypes->max_uses !!}</td>
            <td>
                {!! Form::open(['route' => ['materialTypes.destroy', $materialTypes->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('materialTypes.edit', [$materialTypes->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Estas seguro?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>