routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('items', 'ItemsController');

Route::resource('legajos', 'LegajosController');

Route::resource('tipoTareas', 'TipoTareaController');

Route::resource('tareas', 'TareasController');

Route::get('tareas/filtrar/{status}/{lote}', 'TareasController@index')->name('status');

Route::post('buscarTareas','TareasController@buscarTareas');

Route::resource('stocks', 'StockController');

Route::resource('legajoGps', 'LegajoGpsController');

Route::resource('anomaliases', 'AnomaliasController');

Route::resource('clientes', 'ClientesController');

Route::resource('users', 'UsersController');

Route::get('importarTareas','TareasController@loadTasks');
Route::post('saveRuta','TareasController@saveRuta');

Route::get('modificarRutas','TareasController@modificarRutas');

Route::post('saveRoutes/rutas','TareasController@saveRutas');

Route::post('saveRoutesPolygon/rutas','TareasController@guardarRutasPoly');

Route::resource('inputFormats', 'InputFormatsController');

Route::resource('taskTypes', 'TaskTypesController');

Route::resource('subTasks', 'SubTasksController');

Route::resource('materialTypes', 'MaterialTypesController');

Route::resource('flotillas', 'FlotillasController');

Route::resource('flotillasUsuarios', 'FlotillasUsuariosController');


Route::get('/api/token', 'Api\TokenController@index');

Route::post('/api/user/register', 'Api\UserController@register');
Route::post('/api/user/login', 'Api\UserController@login');
Route::post('/api/user/token_login', 'Api\UserController@token_login');
Route::get('/api/user/logout', 'Api\UserController@logout');
Route::get('/api/fcm/register', 'Api\UserController@fcm_register');
Route::get('/api/user_location', 'Api\LocationController@register_location');
Route::get('/api/user_medidores/{user_id}','Api\UserController@getMedidores');
Route::get('/api/get_face_ids', 'Api\UserController@get_face_ids');
Route::get('/api/download/{file_name}', 'Api\UserController@download_face_ids');

Route::resource('/api/task', 'Api\TaskController');
Route::get('/api/my_task/{id}', 'Api\TaskController@index');
Route::post('/api/task/start', 'Api\TaskController@start_task');
Route::post('/api/task/finish', 'Api\TaskController@finish_task');
Route::post('/api/task/photo', 'Api\TaskController@post_task_photo');
Route::post('/api/task/set_anomaly', 'Api\TaskController@set_anomaly');
Route::get('/api/test', 'Api\TaskController@test');

Route::get('/api/stock/{id}', 'Api\StockController@index');

Route::get('/api/stock_item/{barcode}/{id}', 'Api\StockController@search_item');
Route::post('/api/my_stock_items/check', 'Api\StockController@check_used_item');
Route::get('/api/users/{user_id}', 'Api\UserController@index');

// Order
Route::post('/api/order/process', 'Api\OrderController@process_order');
Route::post('/api/order/accept', 'Api\OrderController@accept_order');
Route::get('/api/order/pending', 'Api\OrderController@get_pending_orders');
Route::get('/api/order/{user_id}', 'Api\OrderController@get_confirm_orders');
Route::get('/api/order/{user_id}/proceeded', 'Api\OrderController@get_proceeded_orders');
Route::get('/api/order/{user_id}/set_check', 'Api\OrderController@set_check_proceeded_orders');
Route::get('/api/order/{user_id}/{order_id}/set_check', 'Api\OrderController@set_check_pended_order');

Route::get('/api/send/{msg}', 'Api\OrderController@send_msg');

Route::get('/seguimiento','FlotillasController@seguimientoGps');
Route::get('/seguir/{id}','FlotillasController@seguir');

Route::resource('marcas', 'MarcasController');

Route::resource('modelos', 'ModelosController');


Route::resource('medidores', 'MedidoresController');
Route::post('medidoresAssign/{id}','MedidoresController@assignTo');
Route::get('changeState/{id}/{state}','MedidoresController@changeState');


Route::post('saveNewGeo','TareasController@newGeo');
Route::post('asignarMedidores','MedidoresController@asignarMultiples');

route::get('imprimirTarea/{id}','TareasController@imprimirTarea');

app/Models/LegajoGps.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class LegajoGps
 * @package App\Models
 * @version June 1, 2018, 2:24 am UTC
 *
 * @property \App\Models\Legajo legajo
 * @property \Illuminate\Database\Eloquent\Collection stock
 * @property integer legajo_id
 * @property string latitude
 * @property string longitude
 */
class LegajoGps extends Model
{
    use SoftDeletes;

    public $table = 'legajo_gps';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'legajo_id',
        'latitude',
        'longitude'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'legajo_id' => 'integer',
        'latitude' => 'string',
        'longitude' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function legajo()
    {
        return $this->belongsTo(\App\Models\Legajo::class);
    }
}

app/Http/Controllers/LegajoGpsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateLegajoGpsRequest;
use App\Http\Requests\UpdateLegajoGpsRequest;
use App\Repositories\LegajoGpsRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class LegajoGpsController extends AppBaseController
{
    /** @var  LegajoGpsRepository */
    private $legajoGpsRepository;

    public function __construct(LegajoGpsRepository $legajoGpsRepo)
    {
        $this->legajoGpsRepository = $legajoGpsRepo;
    }

    /**
     * Display a listing of the LegajoGps.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->legajoGpsRepository->pushCriteria(new RequestCriteria($request));
        $legajoGps = $this->legajoGpsRepository->all();

        return view('legajo_gps.index')
            ->with('legajoGps', $legajoGps);
    }

    /**
     * Show the form for creating a new LegajoGps.
     *
     * @return Response
     */
    public function create()
    {
        return view('legajo_gps.create');
    }

    /**
     * Store a newly created LegajoGps in storage.
     *
     * @param CreateLegajoGpsRequest $request
     *
     * @return Response
     */
    public function store(CreateLegajoGpsRequest $request)
    {
        $input = $request->all();

        $legajoGps = $this->legajoGpsRepository->create($input);

        Flash::success('Legajo Gps saved successfully.');

        return redirect(route('legajoGps.index'));
    }

    /**
     * Display the specified LegajoGps.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $legajoGps = $this->legajoGpsRepository->findWithoutFail($id);

        if (empty($legajoGps)) {
            Flash::error('Legajo Gps not found');

            return redirect(route('legajoGps.index'));
        }

        return view('legajo_gps.show')->with('legajoGps', $legajoGps);
    }

    /**
     * Show the form for editing the specified LegajoGps.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $legajoGps = $this->legajoGpsRepository->findWithoutFail($id);

        if (empty($legajoGps)) {
            Flash::error('Legajo Gps not found');

            return redirect(route('legajoGps.index'));
        }

        return view('legajo_gps.edit')->with('legajoGps', $legajoGps);
    }

    /**
     * Update the specified LegajoGps in storage.
     *
     * @param  int              $id
     * @param UpdateLegajoGpsRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateLegajoGpsRequest $request)
    {
        $legajoGps = $this->legajoGpsRepository->findWithoutFail($id);

        if (empty($legajoGps)) {
            Flash::error('Legajo Gps not found');

            return redirect(route('legajoGps.index'));
        }

        $legajoGps = $this->legajoGpsRepository->update($request->all(), $id);

        Flash::success('Legajo Gps updated successfully.');

        return redirect(route('legajoGps.index'));
    }

    /**
     * Remove the specified LegajoGps from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $legajoGps = $this->legajoGpsRepository->findWithoutFail($id);

        if (empty($legajoGps)) {
            Flash::error('Legajo Gps not found');

            return redirect(route('legajoGps.index'));
        }

        $this->legajoGpsRepository->delete($id);

        Flash::success('Legajo Gps deleted successfully.');

        return redirect(route('legajoGps.index'));
    }
}

resources/views/legajo_gps/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Legajo Gps
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'legajoGps.store']) !!}

                        @include('legajo_gps.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/legajo_gps/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Legajo Gps
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($legajoGps, ['route' => ['legajoGps.update', $legajoGps->id], 'method' => 'patch']) !!}

                        @include('legajo_gps.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/legajo_gps/fields.blade.php
<!-- Legajo Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('legajo_id', 'Legajo Id:') !!}
    {!! Form::number('legajo_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Latitude Field -->
<div class="form-group col-sm-6">
    {!! Form::label('latitude', 'Latitude:') !!}
    {!! Form::text('latitude', null, ['class' => 'form-control']) !!}
</div>

<!-- Longitude Field -->
<div class="form-group col-sm-6">
    {!! Form::label('longitude', 'Longitude:') !!}
    {!! Form::text('longitude', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::Submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('legajoGps.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/legajo_gps/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">GPS de legajo</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('legajoGps.create') !!}">Nuevo</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('legajo_gps.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/legajo_gps/show.blade.php
@extends('layouts.app')

@section('content')
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCXzgMgeX0DrtYECOtubJls3laXBFTvtMQ"></script>
<style>
    #map {
        height: 500px;
        width: 100%;
        position: absolute;
        left: 0;
        top:0;
    }
</style>
    <script>
        @if(!empty($gps))
        $(document).ready(function(){
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 11,
                center: {lat:  -34.5092787, lng: -58.5337791}
            });
            marker = new google.maps.Marker({
                position: new google.maps.LatLng({{$gps->latitude}}, {{$gps->longitude}}),
                map: map,
                animation: google.maps.Animation.DROP,
                icon: {
                    url: '/person.png',
                }

                });
        });
        function pinSymbol(color) {
            return {
                path: 'M 0,0 C -2,-20 -10,-22 -10,-30 A 10,10 0 1,1 10,-30 C 10,-22 2,-20 0,0 z M -2,-30 a 2,2 0 1,1 4,0 2,2 0 1,1 -4,0',
                fillColor: color,
                fillOpacity: 1,
                strokeColor: '#000',
                strokeWeight: 2,
                scale: 1,
            };
        }
        @endif
    </script>
    <section class="content-header">
        <h1>
            Seguimiento: {{$legajo->name}}
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    <div id="map"></div>
                    <a href="{!! route('legajoGps.index') !!}" class="btn btn-default">Atras</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/legajo_gps/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $legajoGps->id !!}</p>
</div>

<!-- Legajo Id Field -->
<div class="form-group">
    {!! Form::label('legajo_id', 'Legajo Id:') !!}
    <p>{!! $legajoGps->legajo_id !!}</p>
</div>

<!-- Latitude Field -->
<div class="form-group">
    {!! Form::label('latitude', 'Latitude:') !!}
    <p>{!! $legajoGps->latitude !!}</p>
</div>

<!-- Longitude Field -->
<div class="form-group">
    {!! Form::label('longitude', 'Longitude:') !!}
    <p>{!! $legajoGps->longitude !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $legajoGps->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $legajoGps->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $legajoGps->deleted_at !!}</p>
</div>

resources/views/legajo_gps/table.blade.php
<table class="table table-responsive" id="legajoGps-table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th colspan="3">Seguir</th>
        </tr>
    </thead>
    <tbody>
    @foreach($legajoGps as $legajoGps)
        <tr>
            <td>{!! $legajoGps->name !!}</td>
            <td>
                <a href="/seguir/{{$legajoGps->id}}"><i class="fa fa-map-marker"></i></a>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>